plugins {
    id("fabric-loom")
}

base {
    archivesName = "${providers.gradleProperty('archives_base_name').get()}-client"
}

dependencies {
    minecraft "com.mojang:minecraft:${providers.gradleProperty('minecraft_version').get()}"
    mappings "net.fabricmc:yarn:${providers.gradleProperty('yarn_mappings').get()}:v2"

    modImplementation "net.fabricmc:fabric-loader:${providers.gradleProperty('loader_version').get()}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${providers.gradleProperty('fabric_version').get()}"

    implementation project(":core")
    implementation project(":serialization")
    implementation project(path: ":networking", configuration: "namedElements")
    implementation project(path: ":minecraft-adapter", configuration: "namedElements")
    implementation project(path: ":services", configuration: "namedElements")
}
