package io.liparakis.chunkis.debug;

public enum ChunkTraceReason {
    NONE,
    DELTA_BECAME_DIRTY,
    DELTA_MARKED_SAVED,
    TRACKER_DIRTY_MAP_PUT,
    TRACKER_UNLOAD_CACHE_HIT,
    TRACKER_UNLOAD_CACHE_MISS,
    TRACKER_MARK_SAVED,
    STALE_GENERATION_IGNORED,
    STORAGE_WRITE,
    STORAGE_READ,
    MISSING_REGION,
    MISSING_ENTRY,
    TRACKER_MEMORY,
    CHUNKIS_STORAGE,
    BOTH,
    NEITHER,
    SPARSE_DELTA_REJECTED,
    VANILLA_STORAGE_BLOCKED,
    OFF_THREAD_MUTATION_REJECTED,
    RESTORE_EMPTY_RESULT,
    RESTORE_EXCEPTION,
    IO_EXCEPTION
}
