package io.liparakis.chunkis.debug;

public enum ChunkTraceReason {
    NONE,
    DELTA_BECAME_DIRTY,
    DELTA_MARKED_SAVED,
    STORAGE_WRITE,
    STORAGE_READ,
    MISSING_REGION,
    MISSING_ENTRY,
    TRACKER_MEMORY,
    CHUNKIS_STORAGE,
    BOTH,
    NEITHER,
    SPARSE_DELTA_REJECTED,
    VANILLA_STORAGE_BLOCKED,
    RESTORE_EMPTY_RESULT,
    RESTORE_EXCEPTION,
    IO_EXCEPTION
}
