package io.liparakis.chunkis.debug;

public enum ChunkTraceEventType {
    SAVE_TX_START,
    VANILLA_SAVE_CANCELLED,
    SAVE_REJECTED,
    SAVE_QUEUED,
    SAVE_FLUSH_STARTED,
    REGION_WRITE_TX_START,
    REGION_WRITE_TX_END,
    SAVE_FLUSH_COMPLETED,
    SAVE_FLUSH_FAILED,
    DELTA_MARKED_DIRTY,
    DELTA_MARKED_CLEAN,
    TRACKER_STATE_UPDATED,
    LOAD_TX_START,
    REGION_READ_TX_START,
    REGION_READ_TX_END,
    LOAD_SOURCE_RESOLVED,
    LOAD_TX_END,
    RESTORE_TX_START,
    RESTORE_COMPLETED,
    RESTORE_FAILED,
    ASSERTION_FAILED
}
