# Gradle Properties
org.gradle.jvmargs=-Xmx24G
org.gradle.daemon=false

# Mod Properties
mod_version=4.0.0
maven_group=io.liparakis.chunkis
archives_base_name=chunkis

# Fabric Properties
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.1
loader_version=0.17.3
fabric_version=0.141.3+1.21.11