package io.liparakis.chunkis.migration.offline;

import static org.junit.jupiter.api.Assertions.assertTrue;

import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.Identifier;
import org.junit.jupiter.api.Test;

/**
 * Test class for {@link OfflineWorldMigrationReport}.
 */
class OfflineWorldMigrationReportTest {

    /**
     * Tests that the JSON representation generated by {@link OfflineWorldMigrationReport#toJsonLine()}
     * contains the expected keys and values, such as the world identifier, handled chunks,
     * and retired regions.
     */
    @Test
    void jsonLineIncludesHandledChunkSummary() {
        final OfflineWorldMigrationReport report = new OfflineWorldMigrationReport(
                RegistryKey.of(RegistryKeys.WORLD, Identifier.ofVanilla("overworld")),
                3,
                512,
                2,
                1
        );

        assertTrue(report.toJsonLine().contains("\"worldId\":\"minecraft:overworld\""));
        assertTrue(report.toJsonLine().contains("\"handledChunks\":512"));
        assertTrue(report.toJsonLine().contains("\"retiredRegions\":1"));
    }
}
