plugins {
    id("java-library")
    id("maven-publish")
}

def modVersion = providers.gradleProperty("mod_version").get()
def mavenGroup = providers.gradleProperty("maven_group").get()
def archivesBaseName = providers.gradleProperty("archives_base_name").get()

group = mavenGroup
version = modVersion

base {
    archivesName = "${archivesBaseName}-cismigrator"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    api             'io.liparakis.chunkis:chunkis-core:3.0.0'
    implementation  'org.slf4j:slf4j-api:2.0.9'

    testImplementation 'com.github.luben:zstd-jni:1.5.7-11'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly    'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        register("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
