plugins {
    id("java-library")
}

base {
    archivesName = "${providers.gradleProperty('archives_base_name').get()}-storage"
}

dependencies {
    api project(":common")
    implementation 'org.slf4j:slf4j-api:2.0.9'
    compileOnly 'org.jetbrains:annotations:26.1.0'

    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.23.0'
    testImplementation 'org.assertj:assertj-core:3.27.7'
}
