package io.liparakis.chunkis.debug.model;

public enum ChunkTraceReason {
    NONE,
    DELTA_BECAME_DIRTY,
    DELTA_MARKED_SAVED,
    TRACKER_DIRTY_MAP_PUT,
    TRACKER_UNLOAD_CACHE_HIT,
    TRACKER_UNLOAD_CACHE_MISS,
    TRACKER_MARK_SAVED,
    TRACKER_UNLOAD_CACHE_PUT,
    TRACKER_UNLOAD_CACHE_INVALIDATED,
    TRACKER_CHUNK_UNLOADED,
    TRACKER_UNLOAD_CACHE_EVICT,
    AUTHORITATIVE_DELTA_KEPT,
    STALE_GENERATION_IGNORED,
    STORAGE_WRITE,
    STORAGE_READ,
    MISSING_REGION, // TODO: emit when region-level load/store paths start tracing missing-region boundaries
    MISSING_ENTRY,
    TRACKER_MEMORY,
    CHUNKIS_STORAGE,
    BOTH,
    NEITHER,
    SPARSE_DELTA_REJECTED,
    VANILLA_STORAGE_BLOCKED, // TODO: emit when vanilla-storage suppression paths are fully traced
    EMPTY_DELTA,
    PLAYER_UNAVAILABLE,
    PAYLOAD_TOO_LARGE,
    INVALID_PAYLOAD,
    CHUNK_NOT_DELTA_CAPABLE,
    CLIENT_WORLD_UNAVAILABLE,
    DECOMPRESSION_FAILED,
    DECODE_FAILED,
    MAPPING_LOOKUP_FAILED,
    OFF_THREAD_MUTATION_REJECTED,
    PASSIVE_CHUNK_DIRTIED,
    SUPPRESSION_CONTEXT_LEAK,
    WATCHED_PAYLOAD_TRACE_INCOMPLETE,
    DECODED_PAYLOAD_NOT_APPLIED,
    DECODED_PAYLOAD_NOT_CONSUMED_BY_WORLD_CONSTRUCTOR,
    DECODED_PAYLOAD_NOT_VISITED_BY_RESTORE,
    RESTORE_SETBLOCK_DID_NOT_APPLY,
    RESTORE_APPLIED_TO_DIFFERENT_CHUNK_INSTANCE,
    WATCHED_ENTITY_UNLOADED_NOT_RELOADED,
    PLAYER_OR_COMMAND_EDIT,
    EXPLICIT_CHUNKIS_MUTATION,
    RESTORE_OF_EXISTING_CHUNKIS_STORAGE,
    BASE_CAPTURE_FOR_EXISTING_CHUNKIS_CHUNK, // TODO: emit when existing-Chunkis base-capture boundaries are traced
    MIGRATION_OF_EXISTING_CHUNKIS_DATA, // TODO: emit when legacy Chunkis migration boundaries are traced
    PASSIVE_VANILLA_LOAD,
    VANILLA_GENERATION, // TODO: emit when vanilla generation boundaries are traced
    VANILLA_POPULATION, // TODO: emit when vanilla population boundaries are traced
    TELEPORT_ONLY_LOAD_UNLOAD, // TODO: emit when teleport-only load/unload boundaries are traced
    CHUNK_SEND_TO_CLIENT, // TODO: emit when client-send boundaries are traced
    VANILLA_AUTOSAVE_UNTOUCHED,
    INTERNAL_RESTORE_BASE_APPLY,
    VANILLA_CANCELLED_WITHOUT_OWNERSHIP, // TODO: emit when ownershipless vanilla-cancel boundaries are traced
    SAVE_WITHOUT_OWNERSHIP,
    RESET_EMPTY_WITHOUT_OWNERSHIP,
    BASE_SNAPSHOT_NOT_APPLIED,
    RESTORE_EMPTY_RESULT,
    RESTORE_EXCEPTION,
    PROTO_DELTA_NOT_RESTORED,
    IO_EXCEPTION
}
