plugins {
    id("java-library")
}

base {
    archivesName = "${providers.gradleProperty('archives_base_name').get()}-common"
}

dependencies {
    api 'it.unimi.dsi:fastutil:8.5.12'
    api 'com.google.code.gson:gson:2.10.1'
    implementation 'org.slf4j:slf4j-api:2.0.9'
    implementation 'com.github.luben:zstd-jni:1.5.7-11'
    compileOnly 'org.jetbrains:annotations:24.1.0'

    testImplementation 'org.mockito:mockito-core:5.23.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.23.0'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation project(":storage")
}
